---
- name: Install and configure Apache HTTP server
  hosts: 192.168.10.107
  become: true
  vars:
    httpd_service_tags: ['httpd']
  tasks:
    - name: Install httpd package
      apt:
        name: apache2
        state: present
      tags:
        - install
        - "{{ httpd_service_tags }}"

    - name: Start and enable httpd service
      service:
        name: apache2
        state: started
        enabled: yes
      tags:
        - service
        - "{{ httpd_service_tags }}"

